### ISSUE TITLE
Caching image space products

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/pfb-clean#29]
Surely this should not make it fall over. Instead if the files don't exist they should be stored under these names

**Comment by landmanbester** [comment]
This is really a caching issue. We need to be able to cache products which are expensive to compute (eg. dirty, psf, interpolated beam) so that we can reuse them when possible. The thing that makes this slightly non-trivial is figuring out when the weights or calibration solutions have changed as this necessitates re-computing the dirty image and psf

**Comment by landmanbester** [comment]
This is now handled in the separate grid worker which computes all data products and writes them to a zarr dataset. In addition, all deconvolution products are written to a separate zarr dataset and all operations performed by deconvolution workers should be reversable
